@startuml
'https://plantuml.com/class-diagram

interface Strategy{
    discount(int price):int
}

class StrategyA implements Strategy{
    + discount(int price):int
}


class StrategyB implements Strategy{
    + discount(int price):int
}

class DiscountContext{
    - Strategy strategy
    + DiscountContext()
    + setStrategy(Strategy strategy):void
    + contextDiscount(int price):int
}

DiscountContext o-- Strategy

@enduml