@startuml
'https://plantuml.com/class-diagram

class UserServiceBean{
    public void save(User user)
    public IDCard getIDCard(Integer userId)
    public void modify()
}
class IDCard
class User
class Department

UserServiceBean --o User
UserServiceBean -- IDCard
UserServiceBean --* Department





@enduml